import {
	Instrument,
	Key,
	NoteDuration,
	Pitch,
	note,
	part,
	rest,
} from "src/types/AudioTypes";

const n = note;
const restAlias = rest;
const partAlias = part;

export const DETECTIVE_SCORE = [
	partAlias(
		"didgeridoo",
		"A.サックス",
		Instrument.BLOCK_NOTE_DIDGERIDOO,
		[
			// イントロ
			// 1
			restAlias(NoteDuration.WHOLE),
			// 2
			restAlias(NoteDuration.HALF),
			n(Pitch.D4, NoteDuration.SIXTEENTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.D4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 3
			restAlias(NoteDuration.HALF),
			n(Pitch.D4, NoteDuration.SIXTEENTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.D4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 4
			restAlias(NoteDuration.HALF),
			n(Pitch.D4, NoteDuration.SIXTEENTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.D4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 5
			n(Pitch.D4, NoteDuration.EIGHTH),
			n(Pitch.ES4, NoteDuration.EIGHTH),
			n(Pitch.E4, NoteDuration.EIGHTH),
			n(Pitch.A4, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH + NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 6
			restAlias(NoteDuration.HALF),
			n(Pitch.D4, NoteDuration.SIXTEENTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.D4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 7
			restAlias(NoteDuration.HALF),
			n(Pitch.D4, NoteDuration.SIXTEENTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.D4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 8
			restAlias(NoteDuration.HALF),
			n(Pitch.D4, NoteDuration.SIXTEENTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.D4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 9
			n(Pitch.G4, NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 10
			n(Pitch.D4, NoteDuration.QUARTER),
			n(Pitch.A4, NoteDuration.HALF),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.D4, NoteDuration.EIGHTH),
			// 11
			n(Pitch.E4, NoteDuration.QUARTER),
			n(Pitch.BS4, NoteDuration.QUARTER),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.EIGHTH + NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 12
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.QUARTER),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 13
			n(Pitch.D4, NoteDuration.QUARTER),
			n(Pitch.G4, NoteDuration.QUARTER),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.E4, NoteDuration.QUARTER),
			n(Pitch.D4, NoteDuration.SIXTEENTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			// 14
			n(Pitch.F4, NoteDuration.POINT_EIGHTH),
			n(Pitch.F4, NoteDuration.THIRTY_SECOND),
			n(Pitch.E4, NoteDuration.THIRTY_SECOND),
			n(Pitch.D4, NoteDuration.QUARTER),
			n(Pitch.A4, NoteDuration.POINT_EIGHTH),
			n(Pitch.A4, NoteDuration.THIRTY_SECOND),
			n(Pitch.G4, NoteDuration.THIRTY_SECOND),
			n(Pitch.F4, NoteDuration.QUARTER),
			// 15
			n(Pitch.G4, NoteDuration.QUARTER),
			n(Pitch.D5, NoteDuration.QUARTER),
			n(Pitch.C5, NoteDuration.QUARTER),
			n(Pitch.BS4, NoteDuration.EIGHTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			// 16~17
			n(Pitch.A4, NoteDuration.WHOLE + NoteDuration.QUARTER),
			// 17
			restAlias(NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 18
			n(Pitch.D4, NoteDuration.POINT_EIGHTH),
			n(Pitch.E4, NoteDuration.THIRTY_SECOND),
			n(Pitch.F4, NoteDuration.THIRTY_SECOND),
			n(Pitch.A4, NoteDuration.HALF),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.D4, NoteDuration.EIGHTH),
			// 19
			n(Pitch.E4, NoteDuration.QUARTER),
			n(Pitch.BS4, NoteDuration.QUARTER),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.EIGHTH + NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 20
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.QUARTER),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.E4, NoteDuration.EIGHTH),
			// 21
			n(Pitch.D4, NoteDuration.QUARTER),
			n(Pitch.G4, NoteDuration.QUARTER),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.E4, NoteDuration.QUARTER),
			n(Pitch.D4, NoteDuration.SIXTEENTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			// 22
			n(Pitch.F4, NoteDuration.POINT_EIGHTH),
			n(Pitch.F4, NoteDuration.THIRTY_SECOND),
			n(Pitch.E4, NoteDuration.THIRTY_SECOND),
			n(Pitch.D4, NoteDuration.POINT_EIGHTH),
			n(Pitch.F4, NoteDuration.THIRTY_SECOND),
			n(Pitch.G4, NoteDuration.THIRTY_SECOND),
			n(Pitch.A4, NoteDuration.POINT_EIGHTH),
			n(Pitch.A4, NoteDuration.THIRTY_SECOND),
			n(Pitch.G4, NoteDuration.THIRTY_SECOND),
			n(Pitch.F4, NoteDuration.QUARTER),
			// 23
			n(Pitch.G4, NoteDuration.QUARTER),
			n(Pitch.D5, NoteDuration.QUARTER),
			n(Pitch.C5, NoteDuration.QUARTER),
			n(Pitch.BS4, NoteDuration.EIGHTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			// 24~25
			n(Pitch.A4, NoteDuration.WHOLE + NoteDuration.QUARTER),
			// 25
			restAlias(NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.A4, NoteDuration.EIGHTH),
			n(Pitch.A4, NoteDuration.EIGHTH),
			// 26
			n(Pitch.F5, NoteDuration.QUARTER),
			n(Pitch.D5, NoteDuration.POINT_QUARTER),
			n(Pitch.DS5, NoteDuration.EIGHTH),
			n(Pitch.D5, NoteDuration.EIGHTH),
			n(Pitch.F5, NoteDuration.EIGHTH),
			// 27
			n(Pitch.E5, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.D5, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C5, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.THIRTY_SECOND),
			n(Pitch.C5, NoteDuration.THIRTY_SECOND),
			// 28~29
			n(Pitch.D5, NoteDuration.POINT_EIGHTH),
			n(Pitch.C5, NoteDuration.THIRTY_SECOND),
			n(Pitch.BS4, NoteDuration.THIRTY_SECOND),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH + NoteDuration.EIGHTH),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.EIGHTH + NoteDuration.POINT_QUARTER),
			// 29
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 30
			n(Pitch.BS4, NoteDuration.QUARTER),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 31~33
			n(Pitch.D5, NoteDuration.QUARTER),
			n(Pitch.C5, NoteDuration.EIGHTH),
			n(Pitch.BS4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C5, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.D5, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.E5, NoteDuration.EIGHTH + NoteDuration.WHOLE + NoteDuration.HALF),
			// 33
			restAlias(NoteDuration.QUARTER),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 34
			n(Pitch.D4, NoteDuration.QUARTER),
			n(Pitch.A4, NoteDuration.HALF),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.D4, NoteDuration.EIGHTH),
			// 35
			n(Pitch.E4, NoteDuration.QUARTER),
			n(Pitch.BS4, NoteDuration.QUARTER),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.EIGHTH + NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 36
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.EIGHTH),
			n(Pitch.BS4, NoteDuration.EIGHTH),
			n(Pitch.C5, NoteDuration.EIGHTH),
			// 37~39
			n(Pitch.D5, NoteDuration.QUARTER),
			n(Pitch.F5, NoteDuration.QUARTER),
			n(Pitch.E5, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.DS5, NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.D5, NoteDuration.EIGHTH + NoteDuration.WHOLE + NoteDuration.HALF),
			// 39~40
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.F4, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.A4, NoteDuration.EIGHTH + NoteDuration.POINT_QUARTER),
			// 40~41
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.BS3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.D4, NoteDuration.EIGHTH + NoteDuration.EIGHTH),
			// 41
			n(Pitch.E4, NoteDuration.EIGHTH),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH + NoteDuration.EIGHTH),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH + NoteDuration.QUARTER),
			// 42~43
			restAlias(NoteDuration.HALF),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.D4, NoteDuration.EIGHTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.F4, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			// 43~44
			restAlias(NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.F4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			// 44~45
			restAlias(NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C5, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			// 45
			n(Pitch.BS4, NoteDuration.EIGHTH),
			n(Pitch.A4, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 46
			restAlias(NoteDuration.POINT_HALF + NoteDuration.EIGHTH),
			n(Pitch.C5, NoteDuration.SIXTEENTH),
			n(Pitch.DS5, NoteDuration.SIXTEENTH),
			// 47
			n(Pitch.D5, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.BS4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.E4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.D4, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 48
			restAlias(NoteDuration.WHOLE),
		],
		1.0,
		0,
		Key.E,
	),
	partAlias(
		"trumpet",
		"トランペット",
		Instrument.BLOCK_NOTE_PLING,
		[
			// イントロ
			// 1
			restAlias(NoteDuration.WHOLE),
			// 2
			restAlias(NoteDuration.HALF),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			n(Pitch.BS4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 3
			restAlias(NoteDuration.HALF),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			n(Pitch.BS4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 4
			restAlias(NoteDuration.HALF),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			n(Pitch.BS4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 5
			n(Pitch.G4, NoteDuration.EIGHTH),
			n(Pitch.AS4, NoteDuration.EIGHTH),
			n(Pitch.A4, NoteDuration.EIGHTH),
			n(Pitch.D5, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C5, NoteDuration.EIGHTH + NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 6
			restAlias(NoteDuration.HALF),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			n(Pitch.BS4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 7
			restAlias(NoteDuration.HALF),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			n(Pitch.BS4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 8
			restAlias(NoteDuration.HALF),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.A4, NoteDuration.SIXTEENTH),
			n(Pitch.BS4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 9
			n(Pitch.G4, NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.GS4, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 10
			restAlias(NoteDuration.WHOLE),
			// 11
			restAlias(NoteDuration.WHOLE),
			// 12
			restAlias(NoteDuration.WHOLE),
			// 13
			restAlias(NoteDuration.WHOLE),
			// 14
			restAlias(NoteDuration.WHOLE),
			// 15
			restAlias(NoteDuration.WHOLE),
			// 16
			restAlias(NoteDuration.WHOLE),
			// 17
			restAlias(NoteDuration.WHOLE),
			// 18
			restAlias(NoteDuration.WHOLE),
			// 19
			restAlias(NoteDuration.WHOLE),
			// 20
			restAlias(NoteDuration.WHOLE),
			// 21
			restAlias(NoteDuration.WHOLE),
			// 22
			restAlias(NoteDuration.WHOLE),
			// 23
			restAlias(NoteDuration.WHOLE),
			// 24
			restAlias(NoteDuration.WHOLE),
			// 25
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.BS4, NoteDuration.EIGHTH + NoteDuration.SIXTEENTH),
			n(Pitch.B4, NoteDuration.POINT_EIGHTH),
			n(Pitch.C5, NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 26
			restAlias(NoteDuration.WHOLE),
			// 27
			restAlias(NoteDuration.WHOLE),
			// 28
			restAlias(NoteDuration.WHOLE),
			// 29
			restAlias(NoteDuration.WHOLE),
			// 30
			restAlias(NoteDuration.WHOLE),
			// 31
			restAlias(NoteDuration.WHOLE),
			// 32
			restAlias(NoteDuration.WHOLE),
			// 33
			restAlias(NoteDuration.WHOLE),
			// 34
			restAlias(NoteDuration.WHOLE),
			// 35
			restAlias(NoteDuration.WHOLE),
			// 36
			restAlias(NoteDuration.WHOLE),
			// 37
			restAlias(NoteDuration.WHOLE),
			// 38
			restAlias(NoteDuration.WHOLE),
			// 39
			restAlias(NoteDuration.WHOLE),
			// 40
			restAlias(NoteDuration.WHOLE),
			// 41
			restAlias(NoteDuration.WHOLE),
			// 42
			restAlias(NoteDuration.WHOLE),
			// 43
			restAlias(NoteDuration.WHOLE),
			// 44
			restAlias(NoteDuration.WHOLE),
			// 45
			restAlias(NoteDuration.WHOLE),
			// 46
			restAlias(NoteDuration.WHOLE),
			// 47
			restAlias(NoteDuration.WHOLE),
			// 48
			restAlias(NoteDuration.WHOLE),
		],
		0.8,
		0,
		Key.Bb,
	),
	partAlias(
		"piano",
		"ピアノ",
		Instrument.BLOCK_NOTE_HARP,
		[
			// イントロ
			// 1
			restAlias(NoteDuration.WHOLE),
			// 2
			restAlias(NoteDuration.WHOLE),
			// 3
			restAlias(NoteDuration.WHOLE),
			// 4
			restAlias(NoteDuration.WHOLE),
			// 5
			restAlias(NoteDuration.WHOLE),
			// 6
			restAlias(NoteDuration.WHOLE),
			// 7
			restAlias(NoteDuration.WHOLE),
			// 8
			restAlias(NoteDuration.WHOLE),
			// 9
			restAlias(NoteDuration.WHOLE),
			// 10
			restAlias(NoteDuration.WHOLE),
			// 11
			restAlias(NoteDuration.WHOLE),
			// 12
			restAlias(NoteDuration.WHOLE),
			// 13
			restAlias(NoteDuration.WHOLE),
			// 14
			restAlias(NoteDuration.WHOLE),
			// 15
			restAlias(NoteDuration.WHOLE),
			// 16
			restAlias(NoteDuration.WHOLE),
			// 17
			restAlias(NoteDuration.WHOLE),
			// 18
			restAlias(NoteDuration.WHOLE),
			// 19
			restAlias(NoteDuration.WHOLE),
			// 20
			restAlias(NoteDuration.WHOLE),
			// 21
			restAlias(NoteDuration.WHOLE),
			// 22
			restAlias(NoteDuration.WHOLE),
			// 23
			restAlias(NoteDuration.WHOLE),
			// 24
			restAlias(NoteDuration.WHOLE),
			// 25
			restAlias(NoteDuration.WHOLE),
			// 26
			restAlias(NoteDuration.WHOLE),
			// 27
			restAlias(NoteDuration.WHOLE),
			// 28
			restAlias(NoteDuration.WHOLE),
			// 29
			restAlias(NoteDuration.WHOLE),
			// 30
			restAlias(NoteDuration.WHOLE),
			// 31
			restAlias(NoteDuration.WHOLE),
			// 32
			restAlias(NoteDuration.WHOLE),
			// 33
			restAlias(NoteDuration.WHOLE),
			// 34
			restAlias(NoteDuration.WHOLE),
			// 35
			restAlias(NoteDuration.WHOLE),
			// 36
			restAlias(NoteDuration.WHOLE),
			// 37
			restAlias(NoteDuration.WHOLE),
			// 38
			restAlias(NoteDuration.HALF),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.AS4, NoteDuration.SIXTEENTH),
			n(Pitch.F5, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 39
			restAlias(NoteDuration.HALF),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.AS4, NoteDuration.SIXTEENTH),
			n(Pitch.F5, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 40
			restAlias(NoteDuration.HALF),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.AS4, NoteDuration.SIXTEENTH),
			n(Pitch.F5, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 41
			restAlias(NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.GS4, NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH),
			n(Pitch.C4, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			// 42
			restAlias(NoteDuration.HALF),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.AS4, NoteDuration.SIXTEENTH),
			n(Pitch.F5, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 43
			restAlias(NoteDuration.HALF),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.AS4, NoteDuration.SIXTEENTH),
			n(Pitch.F5, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 44
			restAlias(NoteDuration.HALF),
			n(Pitch.F4, NoteDuration.SIXTEENTH),
			n(Pitch.G4, NoteDuration.SIXTEENTH),
			n(Pitch.AS4, NoteDuration.SIXTEENTH),
			n(Pitch.F5, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 45
			n(Pitch.G4, NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.G4, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 46
			restAlias(NoteDuration.WHOLE),
			// 47
			restAlias(NoteDuration.WHOLE),
			// 48
			restAlias(NoteDuration.WHOLE),
		],
		0.4,
		0,
	),
	partAlias(
		"piano2",
		"ピアノ2",
		Instrument.BLOCK_NOTE_HARP,
		[
			// イントロ
			// 1
			restAlias(NoteDuration.WHOLE),
			// 2
			restAlias(NoteDuration.WHOLE),
			// 3
			restAlias(NoteDuration.WHOLE),
			// 4
			restAlias(NoteDuration.WHOLE),
			// 5
			restAlias(NoteDuration.WHOLE),
			// 6
			restAlias(NoteDuration.WHOLE),
			// 7
			restAlias(NoteDuration.WHOLE),
			// 8
			restAlias(NoteDuration.WHOLE),
			// 9
			restAlias(NoteDuration.WHOLE),
			// 10
			restAlias(NoteDuration.WHOLE),
			// 11
			restAlias(NoteDuration.WHOLE),
			// 12
			restAlias(NoteDuration.WHOLE),
			// 13
			restAlias(NoteDuration.WHOLE),
			// 14
			restAlias(NoteDuration.WHOLE),
			// 15
			restAlias(NoteDuration.WHOLE),
			// 16
			restAlias(NoteDuration.WHOLE),
			// 17
			restAlias(NoteDuration.WHOLE),
			// 18
			restAlias(NoteDuration.WHOLE),
			// 19
			restAlias(NoteDuration.WHOLE),
			// 20
			restAlias(NoteDuration.WHOLE),
			// 21
			restAlias(NoteDuration.WHOLE),
			// 22
			restAlias(NoteDuration.WHOLE),
			// 23
			restAlias(NoteDuration.WHOLE),
			// 24
			restAlias(NoteDuration.WHOLE),
			// 25
			restAlias(NoteDuration.WHOLE),
			// 26
			restAlias(NoteDuration.WHOLE),
			// 27
			restAlias(NoteDuration.WHOLE),
			// 28
			restAlias(NoteDuration.WHOLE),
			// 29
			restAlias(NoteDuration.WHOLE),
			// 30
			restAlias(NoteDuration.WHOLE),
			// 31
			restAlias(NoteDuration.WHOLE),
			// 32
			restAlias(NoteDuration.WHOLE),
			// 33
			restAlias(NoteDuration.WHOLE),
			// 34
			restAlias(NoteDuration.WHOLE),
			// 35
			restAlias(NoteDuration.WHOLE),
			// 36
			restAlias(NoteDuration.WHOLE),
			// 37
			restAlias(NoteDuration.WHOLE),
			// 38
			restAlias(NoteDuration.HALF),
			n(Pitch.F5, NoteDuration.SIXTEENTH),
			n(Pitch.G5, NoteDuration.SIXTEENTH),
			n(Pitch.AS5, NoteDuration.SIXTEENTH),
			n(Pitch.F6, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 39
			restAlias(NoteDuration.HALF),
			n(Pitch.F5, NoteDuration.SIXTEENTH),
			n(Pitch.G5, NoteDuration.SIXTEENTH),
			n(Pitch.AS5, NoteDuration.SIXTEENTH),
			n(Pitch.F6, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 40
			restAlias(NoteDuration.HALF),
			n(Pitch.F5, NoteDuration.SIXTEENTH),
			n(Pitch.G5, NoteDuration.SIXTEENTH),
			n(Pitch.AS5, NoteDuration.SIXTEENTH),
			n(Pitch.F6, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 41
			restAlias(NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.GS5, NoteDuration.EIGHTH),
			n(Pitch.G5, NoteDuration.EIGHTH),
			n(Pitch.C5, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			// 42
			restAlias(NoteDuration.HALF),
			n(Pitch.F5, NoteDuration.SIXTEENTH),
			n(Pitch.G5, NoteDuration.SIXTEENTH),
			n(Pitch.AS5, NoteDuration.SIXTEENTH),
			n(Pitch.F6, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 43
			restAlias(NoteDuration.HALF),
			n(Pitch.F5, NoteDuration.SIXTEENTH),
			n(Pitch.G5, NoteDuration.SIXTEENTH),
			n(Pitch.AS5, NoteDuration.SIXTEENTH),
			n(Pitch.F6, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 44
			restAlias(NoteDuration.HALF),
			n(Pitch.F5, NoteDuration.SIXTEENTH),
			n(Pitch.G5, NoteDuration.SIXTEENTH),
			n(Pitch.AS5, NoteDuration.SIXTEENTH),
			n(Pitch.F6, NoteDuration.SIXTEENTH + NoteDuration.POINT_EIGHTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 45
			n(Pitch.C5, NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C5, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 46
			restAlias(NoteDuration.WHOLE),
			// 47
			restAlias(NoteDuration.WHOLE),
			// 48
			restAlias(NoteDuration.WHOLE),
		],
		0.4,
		0,
	),
	partAlias(
		"piano3",
		"ピアノ3",
		Instrument.BLOCK_NOTE_HARP,
		[
			// イントロ
			// 1
			restAlias(NoteDuration.WHOLE),
			// 2
			restAlias(NoteDuration.WHOLE),
			// 3
			restAlias(NoteDuration.WHOLE),
			// 4
			restAlias(NoteDuration.WHOLE),
			// 5
			restAlias(NoteDuration.WHOLE),
			// 6
			restAlias(NoteDuration.WHOLE),
			// 7
			restAlias(NoteDuration.WHOLE),
			// 8
			restAlias(NoteDuration.WHOLE),
			// 9
			restAlias(NoteDuration.WHOLE),
			// 10
			restAlias(NoteDuration.WHOLE),
			// 11
			restAlias(NoteDuration.WHOLE),
			// 12
			restAlias(NoteDuration.WHOLE),
			// 13
			restAlias(NoteDuration.WHOLE),
			// 14
			restAlias(NoteDuration.WHOLE),
			// 15
			restAlias(NoteDuration.WHOLE),
			// 16
			restAlias(NoteDuration.WHOLE),
			// 17
			restAlias(NoteDuration.WHOLE),
			// 18
			restAlias(NoteDuration.WHOLE),
			// 19
			restAlias(NoteDuration.WHOLE),
			// 20
			restAlias(NoteDuration.WHOLE),
			// 21
			restAlias(NoteDuration.WHOLE),
			// 22
			restAlias(NoteDuration.WHOLE),
			// 23
			restAlias(NoteDuration.WHOLE),
			// 24
			restAlias(NoteDuration.WHOLE),
			// 25
			restAlias(NoteDuration.WHOLE),
			// 26
			restAlias(NoteDuration.WHOLE),
			// 27
			restAlias(NoteDuration.WHOLE),
			// 28
			restAlias(NoteDuration.WHOLE),
			// 29
			restAlias(NoteDuration.WHOLE),
			// 30
			restAlias(NoteDuration.WHOLE),
			// 31
			restAlias(NoteDuration.WHOLE),
			// 32
			restAlias(NoteDuration.WHOLE),
			// 33
			restAlias(NoteDuration.WHOLE),
			// 34
			restAlias(NoteDuration.WHOLE),
			// 35
			restAlias(NoteDuration.WHOLE),
			// 36
			restAlias(NoteDuration.WHOLE),
			// 37
			restAlias(NoteDuration.WHOLE),
			// 38
			restAlias(NoteDuration.WHOLE),
			// 39
			restAlias(NoteDuration.WHOLE),
			// 40
			restAlias(NoteDuration.WHOLE),
			// 41
			restAlias(NoteDuration.WHOLE),
			// 42
			restAlias(NoteDuration.WHOLE),
			// 43
			restAlias(NoteDuration.WHOLE),
			// 44
			restAlias(NoteDuration.WHOLE),
			// 45
			n(Pitch.F5, NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.E5, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 46
			restAlias(NoteDuration.WHOLE),
			// 47
			restAlias(NoteDuration.WHOLE),
			// 48
			restAlias(NoteDuration.WHOLE),
		],
		0.4,
		0,
	),
	partAlias(
		"base",
		"ベース",
		Instrument.BLOCK_NOTE_GUITAR,
		[
			// イントロ
			// 1
			restAlias(NoteDuration.WHOLE),
			// 2
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			// 3
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			// 4
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			// 5
			n(Pitch.C2, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.EIGHTH + NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			// 6
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			// 7
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			// 8
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			// 9
			n(Pitch.C2, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 10
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			// 11
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			// 12
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			// 13
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			// 14
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			// 15
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS2, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS2, NoteDuration.EIGHTH),
			// 16
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.BS1, NoteDuration.EIGHTH),
			// 17
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.EIGHTH),
			n(Pitch.GS1, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.G1, NoteDuration.EIGHTH),
			// 18
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			// 19
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			// 20
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			// 21
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS1, NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.G1, NoteDuration.EIGHTH),
			// 22
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			// 23
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS2, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS2, NoteDuration.EIGHTH),
			// 24
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.BS1, NoteDuration.EIGHTH),
			// 25
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C2, NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.G1, NoteDuration.EIGHTH),
			// 26
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			// 27
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.D1, NoteDuration.EIGHTH),
			// 28
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.EIGHTH),
			n(Pitch.BS1, NoteDuration.EIGHTH),
			// 29
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS1, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.A1, NoteDuration.EIGHTH),
			// 30
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS2, NoteDuration.EIGHTH),
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS2, NoteDuration.EIGHTH),
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS1, NoteDuration.SIXTEENTH),
			n(Pitch.BS2, NoteDuration.EIGHTH),
			n(Pitch.BS1, NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.EIGHTH),
			// 31~32
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.AS3, NoteDuration.EIGHTH),
			n(Pitch.G1, NoteDuration.EIGHTH + NoteDuration.EIGHTH),
			// 32
			n(Pitch.G2, NoteDuration.SIXTEENTH),
			n(Pitch.G2, NoteDuration.SIXTEENTH),
			n(Pitch.G1, NoteDuration.EIGHTH),
			n(Pitch.G2, NoteDuration.SIXTEENTH),
			n(Pitch.G2, NoteDuration.SIXTEENTH),
			n(Pitch.G1, NoteDuration.EIGHTH),
			n(Pitch.G2, NoteDuration.SIXTEENTH),
			n(Pitch.G2, NoteDuration.SIXTEENTH),
			n(Pitch.G1, NoteDuration.EIGHTH),
			n(Pitch.G2, NoteDuration.SIXTEENTH),
			n(Pitch.G2, NoteDuration.SIXTEENTH),
			// 33
			n(Pitch.C2, NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 34
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.EIGHTH),
			// 35
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES3, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES1, NoteDuration.EIGHTH),
			// 36
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			// 37
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.EIGHTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.G1, NoteDuration.EIGHTH),
			n(Pitch.E1, NoteDuration.EIGHTH),
			// 38
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			// 39
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			// 40
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			// 41
			n(Pitch.C2, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.EIGHTH + NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.EIGHTH),
			// 42
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.EIGHTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			n(Pitch.F1, NoteDuration.SIXTEENTH),
			// 43
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.EIGHTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			n(Pitch.AS1, NoteDuration.SIXTEENTH),
			// 44
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.EIGHTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			n(Pitch.DS2, NoteDuration.SIXTEENTH),
			// 45
			n(Pitch.C2, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C2, NoteDuration.EIGHTH + NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 46
			n(Pitch.F1, NoteDuration.HALF + NoteDuration.POINT_QUARTER),
			n(Pitch.ES3, NoteDuration.SIXTEENTH),
			n(Pitch.E3, NoteDuration.SIXTEENTH),
			// 47
			n(Pitch.F3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.DS3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.BS2, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.G2, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.AS2, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.F2, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			// 48
			restAlias(NoteDuration.WHOLE),
		],
		0.4,
		0,
	),
	partAlias(
		"bassDrum",
		"バスドラム",
		Instrument.BLOCK_NOTE_SNARE,
		[
			// イントロ
			// 1
			restAlias(NoteDuration.WHOLE),
			// 2
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 3
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 4
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 5
			n(Pitch.D1, NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.D1, NoteDuration.EIGHTH),
			restAlias(NoteDuration.HALF),
			// 6
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 7
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 8
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 9
			n(Pitch.D1, NoteDuration.POINT_QUARTER),
			n(Pitch.D1, NoteDuration.EIGHTH),
			restAlias(NoteDuration.HALF),
			// 10
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 11
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 12
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 13
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 14
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 15
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 16
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 17
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 18
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 19
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 20
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 21
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 22
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 23
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 24
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 25
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 26
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 27
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 28
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 29
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 30
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 31
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 32
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 33
			n(Pitch.D1, NoteDuration.POINT_QUARTER),
			n(Pitch.D1, NoteDuration.EIGHTH),
			restAlias(NoteDuration.HALF),
			// 34
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 35
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 36
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 37
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 38
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 39
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 40
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 41
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 42
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 43
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 44
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 45
			n(Pitch.D1, NoteDuration.POINT_QUARTER),
			n(Pitch.D1, NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 46
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 47
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			n(Pitch.D1, NoteDuration.QUARTER),
			// 48
			restAlias(NoteDuration.WHOLE),
		],
		0.1,
		0,
	),
	partAlias(
		"snare",
		"スネアドラム",
		Instrument.BLOCK_NOTE_SNARE,
		[
			// イントロ
			// 1
			restAlias(NoteDuration.HALF),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			// 2
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 3
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 4
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 5
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			n(Pitch.ES2, NoteDuration.SIXTEENTH),
			// 6
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 7
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 8
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 9
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.HALF),
			// 10
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 11
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 12
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 13
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 14
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 15
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 16
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 17
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 18
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 19
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 20
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 21
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 22
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 23
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 24
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 25
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 26
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 27
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 28
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 29
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 30
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 31
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 32
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			// 33
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 34
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 35
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 36
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 37
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 38
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 39
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 40
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 41
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 42
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 43
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 44
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 45
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.QUARTER),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 46
			restAlias(NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			restAlias(NoteDuration.QUARTER),
			// 47
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			n(Pitch.ES2, NoteDuration.EIGHTH),
			// 48
			restAlias(NoteDuration.WHOLE),
		],
		0.3,
		0,
	),
	partAlias(
		"hi-hat",
		"ハイハット",
		Instrument.BLOCK_IRON_TRAPDOOR_OPEN,
		[
			// イントロ
			// 1
			restAlias(NoteDuration.WHOLE),
			// 2
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 3
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 4
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			// 5
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.HALF),
			// 6
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 7
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 8
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			// 9
			restAlias(NoteDuration.WHOLE),
			// 10
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 11
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 12
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 13
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 14
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 15
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 16
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 17
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 18
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 19
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 20
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 21
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 22
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 23
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 24
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 25
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 26
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 27
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 28
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 29
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 30
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 31
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			// 32
			restAlias(NoteDuration.WHOLE),
			// 33
			restAlias(NoteDuration.WHOLE),
			// 34
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 35
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 36
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 37
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 38
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 39
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 40
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 41
			restAlias(NoteDuration.HALF),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 42
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 43
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 44
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 45
			restAlias(NoteDuration.HALF),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.SIXTEENTH),
			restAlias(NoteDuration.SIXTEENTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 46
			restAlias(NoteDuration.WHOLE),
			// 47
			restAlias(NoteDuration.WHOLE),
			// 48
			restAlias(NoteDuration.WHOLE),
		],
		0.4,
		0,
	),
	partAlias(
		"ride",
		"ライドシンバル",
		Instrument.BLOCK_ANVIL_LAND,
		[
			// イントロ
			// 1
			restAlias(NoteDuration.WHOLE),
			// 2
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.POINT_HALF),
			// 3
			restAlias(NoteDuration.WHOLE),
			// 4
			restAlias(NoteDuration.WHOLE),
			// 5
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.HALF),
			// 6
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.POINT_HALF),
			// 7
			restAlias(NoteDuration.WHOLE),
			// 8
			restAlias(NoteDuration.WHOLE),
			// 9
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.HALF),
			// 10
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.POINT_HALF),
			// 11
			restAlias(NoteDuration.WHOLE),
			// 12
			restAlias(NoteDuration.WHOLE),
			// 13
			restAlias(NoteDuration.WHOLE),
			// 14
			restAlias(NoteDuration.WHOLE),
			// 15
			restAlias(NoteDuration.WHOLE),
			// 16
			restAlias(NoteDuration.WHOLE),
			// 17
			restAlias(NoteDuration.WHOLE),
			// 18
			restAlias(NoteDuration.WHOLE),
			// 19
			restAlias(NoteDuration.WHOLE),
			// 20
			restAlias(NoteDuration.WHOLE),
			// 21
			restAlias(NoteDuration.WHOLE),
			// 22
			restAlias(NoteDuration.WHOLE),
			// 23
			restAlias(NoteDuration.WHOLE),
			// 24
			restAlias(NoteDuration.WHOLE),
			// 25
			restAlias(NoteDuration.WHOLE),
			// 26
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.POINT_HALF),
			// 27
			restAlias(NoteDuration.WHOLE),
			// 28
			restAlias(NoteDuration.WHOLE),
			// 29
			restAlias(NoteDuration.WHOLE),
			// 30
			restAlias(NoteDuration.WHOLE),
			// 31
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.POINT_HALF),
			n(Pitch.C3, NoteDuration.EIGHTH),
			// 32
			restAlias(NoteDuration.WHOLE),
			// 33
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.HALF),
			// 34
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.POINT_HALF),
			// 35
			restAlias(NoteDuration.WHOLE),
			// 36
			restAlias(NoteDuration.WHOLE),
			// 37
			restAlias(NoteDuration.WHOLE),
			// 38
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.POINT_HALF),
			// 39
			restAlias(NoteDuration.WHOLE),
			// 40
			restAlias(NoteDuration.WHOLE),
			// 41
			n(Pitch.C3, NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.HALF),
			// 42
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.EIGHTH),
			restAlias(NoteDuration.POINT_HALF),
			// 43
			restAlias(NoteDuration.WHOLE),
			// 44
			restAlias(NoteDuration.WHOLE),
			// 45
			n(Pitch.C3, NoteDuration.QUARTER),
			restAlias(NoteDuration.EIGHTH),
			n(Pitch.C3, NoteDuration.EIGHTH),
			restAlias(NoteDuration.HALF),
			// 46
			n(Pitch.C3, NoteDuration.QUARTER),
			restAlias(NoteDuration.POINT_HALF),
			// 47
			restAlias(NoteDuration.WHOLE),
			// 48
			restAlias(NoteDuration.WHOLE),
		],
		0.2,
		0,
	),
];
